name: General
description: General issue report or feature request.
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > * Update plugin to the newest version, perhaps the problem has already been solved.
        > * Check plugin homepage (readme).
        > * Avoid duplicating any existing issues which already track or resolve your problem, search the existing issues first (open and closed).
        > * Aim to find a descriptive and precise title for your report.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide a clear and concise description. Be sure to include:
        * What is happening?
        * What you expect to happen?
        * Clear steps explaining how to reproduce the problem.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: code
      description: |
        If relevant to your report, include your logs.
        * You can enable more logs, set all logs in plugin config and debug mode in Homebridge settings.
        * Keep this short. Do not paste in hundreds of lines repeating the same error.
        * Show the logs from the service being restarted until the error occurs.
        * Remove any sensitive data (like login details).
    validations:
      required: false
  - type: textarea
    id: device-status
    attributes:
      label: Device status
      render: JSON
      description: |
        If relevant to your report, include your device status. 
        * To get device status: enable all logs in plugin config and debug mode in Homebridge setting, device status will be in logs every time plugin refresh device status.
        * Be sure to remove any sensitive information (passwords, tokens, etc.).
    validations:
      required: false    
  - type: textarea
    id: plugin-config
    attributes:
      label: Plugin config
      render: JSON
      description: |
        If relevant to your report, include your plugin config. 
        * Be sure to remove any sensitive information (passwords, tokens, etc.).
    validations:
      required: false
  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: |
        E.G.: 4.4.2
    validations:
      required: true
