# This workflow tags the latest commit with the version
# from package.json if that tag doesn't yet exist.
#
# The created tag can be used by deployment workflows
# to create releases and publish the plugin to npm.
#
# Example: If we push or merge changes onto `master` and package.json
# contains the version "1.3.0", we will tag the commit with "v1.3.0".

name: Tag commit

on:
  push:
    branches:
      - master

jobs:
  tag-commit:
    name: Tag commit
    runs-on: ubuntu-latest
    uses: actions/checkout@v4

    steps:
      - name: Get version from package.json
        id: get-version
        run: |
          version=$(jq -r .version package.json)
          echo "The package.json version is: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Configure Git
        run: |
          git config --global user.email "embee8@users.noreply.github.com"
          git config --global user.name "embee8"

      - name: Create tag
        id: create-tag
        run: |
          tag="v${{ steps.get-version.outputs.version }}"
          echo "Tagging commit with: ${tag}"
          git tag "${tag}"

      - name: Push tag
        id: push-tag
        run: |
          git push origin "${tag}"
